apiVersion: v2
name: codedx-tool-orchestration
version: 1.8.0
appVersion: "1.5.0"
description: A Helm chart for Code Dx Tool Orchestration
icon: https://codedx.com/wp-content/uploads/2017/03/CodeDx-logo.png
home: https://github.com/codedx/codedx-kubernetes
keywords:
- codedx
- tool
- orchestration
sources:
dependencies:
- name: argo
  version: 0.14.1
  repository: https://codedx.github.io/codedx-kubernetes
- name: minio
  version: 3.1.6
  repository: https://codedx.github.io/codedx-kubernetes
maintainers:
- name: tylercamp
  email: support@codedx.com
- name: ssalas
  email: support@codedx.com
